apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
spec:
  selector:
    matchLabels:
      app: node-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
      - name: node-backend
        image: backend:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: node-backend
  ports:
  - port: 3000
    targetPort: 3000